### ISSUE TITLE
Dataset - Water column CO2 system measurements from January 2016 to December 2023 from Hakai Institute oceanographic station QU39 in northern Strait of Georgia, British Columbia, Canada

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#111]
## Water column CO2 system measurements from January 2016 to December 2023 from Hakai Institute oceanographic station QU39 in northern Strait of Georgia, British Columbia, Canada

<https://hakaiinstitute.github.io/hakai-metadata-entry-form/#/en/hakai/RLSJmX44tkZoh8ncSpZECUoikBt1/-O6XpUwSfsllQlTBMz53>

### In General

- [x] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [x] No version information in the title
- [x] Frontloaded (with the most important information first)
- [x] Include the geographical region the data apply to
- [ ] Short – aim for 60 characters including spaces
- [x] Does not include acronyms – put these in the keywords
- [x] Does not include the word “dataset”
- [ ] Time series datasets should include “time series” at the end of the title

#### Abstract

- [x] Abbreviations have been expanded upon at first mention
- [x] Abstract describes how, when, what, where, why of data collection and is limited to no more than 500 words

#### DOI

- [x] A DOI has been drafted for this record
- [x] DOI has been updated via the form after review and changes to record
- [x] DOI has been manually edited on datacite fabrica
- [x] DOI status has been changed from Draft to Findable

### Spatial

- [x] Ensure that Depth or Height Positive is correctly selected

### Contact

- [x] ROR and ORCID(s) are included and linked properly where applicable
- [x] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [x] Include Hakai Institute as Publisher and include data@hakai.org as email
- [x] Make sure email address is provided if the role is 'Metadata Custodian' or 'Point of Contact' 
- [x] Add contact affiliation where known including ROR
- [x] If resource is (partially) generated by Hakai researchers, include 'Tula Foundation' (with associated ROR) with 'Funder' role. Be sure to uncheck 'include in citation' for Tula Foundation.

### Resources

- [x] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [x] Readme, changelog, data dictionary, protocols included in data-package (for tabular text based data)
- [ ] An archive folder, or other means, for older data versions is included in the data package if the version is _not_ 1.0
- [x] Links work
- [ ] All files in the data package can be opened and are not corrupt
- [x] No executable files in the data package. Files should be open formats and standards (.csv, .txt for example)

**Comment by timvdstap** [comment]
Hi @WileyEvans , few comments (I will also email this):

- In the abstract you make reference to Campbell et al. (2023) for the sampling collection/analysis protocol. I have included this reference also in the Data & Documentation section.
- The Data & Documentation section now also links to the data from 2016/2017 (https://doi.org/10.21966/1.715738), with the relation type 'Obsoletes' (i.e., this resource obsoletes the resource from 2016/2017). Please note that this doesn't _delete_ that record.
- I see in your readme that you've included references to method and other reports - would you want those included in the related works section of your record? 
- I have parsed out your keywords (you have to press enter following each individual keyword/phrase).
- If you decide to leave the time range in the title, I would change the dataset status to 'completed' and include the end date when data was last collected. If you keep the status as 'ongoing', I would remove the time range from the title, replacing it with 'time series'. 
- I've added version number (1.0). This'll be important especially if you are considering adding data to this data record in the future, producing a new (minor) version of the data. 
- Is there a specific reason behind having Open Government License - Canada as the license? I mainly ask because the default license in the Hakai repository template is [CC-BY-4.0](https://github.com/HakaiInstitute/QU39_inorganic_carbon_data_2016_2023/blob/main/LICENSE) and so we then we might have to change that.
- I have changed your, Katie's and Carrie's affiliation to Hakai Institute. This way we can have its ROR associated. The email associated with the affiliation I've changed to the generic 'data@hakai.org'. Emails to individual contacts are listed under their individual information. 
- I have added Hakai Institute as 'Publisher', you'll this reflected in the citation as well (behind the version number).
- I have added 'Tula Foundation' as 'Funder', but making sure this is does not appear in the citation. 
- There's currently two data-dictionary files in the root of your repository, you can remove the data-dictionary.csv file. 
- I will email you how to create additional folders in your repository where you can include your data files.

**Comment by timvdstap** [comment]
Published: https://doi.org/10.21966/k1xg-6920

**Comment by fostermh** [comment]
it appears the DOI points to the wrong URL. doi redirects to: 
https://catalogue.hakai.org/dataset/ca-cioos_355467ad-104d-40a6-b06e-52a67bfe247e

while the actual record is at:
https://catalogue.hakai.org/dataset/ca-cioos_48c8f830-f281-4ca1-9a81-ea690e70cb7a

**Comment by timvdstap** [comment]
The record at https://catalogue.hakai.org/dataset/ca-cioos_48c8f830-f281-4ca1-9a81-ea690e70cb7a is made obsolete by this record submission. It is included as a related work (relation type: 'obsoletes'). I'm not sure why it points to that record, it definitely shouldn't.

**Comment by timvdstap** [comment]
Turns out there were point coordinates added in the polygon field and this was missed throughout review. Resolved.
