### ISSUE TITLE
Dataset - Fraser River Landslide Project - 2022-2024 - Drone Data - Hakai Institute

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#116]
## Fraser River Landslide Project - 2022-2024 - Drone Data - Hakai Institute

<https://hakaiinstitute.github.io/hakai-metadata-entry-form/#/en/hakai/RvRPlFMSsIaBwoGdQIq5BVYfBBa2/-NpurN_vwkhOgSJmgBh9>

### In General

- [x] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [x] No version information in the title
- [x] Frontloaded (with the most important information first)
- [x] Include the geographical region the data apply to
- [x] Short – aim for 60 characters including spaces
- [x] Does not include acronyms – put these in the keywords
- [x] Does not include the word “dataset”
- [ ] Time series datasets should include “time series” at the end of the title

#### Abstract

- [x] Abbreviations have been expanded upon at first mention
- [x] Abstract describes how, when, what, where, why of data collection and is limited to no more than 500 words

#### DOI

- [x] A DOI has been drafted for this record
- [x] DOI has been updated via the form after review and changes to record
- [ ] DOI has been manually edited on datacite fabrica
- [ ] DOI status has been changed from Draft to Findable

### Spatial

- [x] Ensure that Depth or Height Positive is correctly selected

### Contact

- [x] ROR and ORCID(s) are included and linked properly where applicable
- [ ] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [x] Include Hakai Institute as Publisher and include data@hakai.org as email
- [x] Make sure email address is provided if the role is 'Metadata Custodian' or 'Point of Contact' 
- [x] Add contact affiliation where known including ROR
- [x] If resource is (partially) generated by Hakai researchers, include 'Tula Foundation' (with associated ROR) with 'Funder' role. Be sure to uncheck 'include in citation' for Tula Foundation.

### Resources

- [ ] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [ ] Readme, changelog, data dictionary, protocols included in data-package (for tabular text based data)
- [ ] An archive folder, or other means, for older data versions is included in the data package if the version is _not_ 1.0
- [x] Links work
- [ ] All files in the data package can be opened and are not corrupt
- [x] No executable files in the data package. Files should be open formats and standards (.csv, .txt for example)

**Comment by timvdstap** [comment]
Hey @hakaiholmes some thoughts / recommendations:

- [ ] Personally, I would remove 'Hakai Institute' from the title, but instead include it as the publishing institute so that it still appears in the recommended citation (see next item).
- [ ] Have the 'Hakai Institute' with role: **Publisher** appear in the citation (checking the box)
- [ ] Jeremy Venditti and Brian Menounos are currently not included as contacts - should they be, if they are large partners on this project? Looking at the mapping report, I also see the names Julia Carr, Aaron Steelquist and Erin Seagren - should they be given attribution as well?
- [ ] I don't think the `data@hakai.org` will show up in the metadata record if no additional individual information is provided (first + last name etc). 
- [ ] I know I'm starting to sound like a broken record, but I would consider being more explicit in the author list, especially if this is spelled out in greater detail in the metadata report. In the current format the people included in the metadata report don't receive any attribution.
- [ ] Should the DJI Mavic 3 drone also be included as a platform?
- [ ] Can the data be requested? If so, how (is there an online request form that users can fill out, or do they need to email someone)?

**Comment by hakaiholmes** [comment]
Thank you for those edits. Most have been made. I stuck with the drone side of things for the contacts on this record. The larger report will have Jeremy et al included. 
Almost ready to publish again here.

**Comment by timvdstap** [comment]
Sounds good, thanks Keith, let me know when you'd like to do another quick review!

**Comment by hakaiholmes** [comment]
1 - let me check on those dates.
2 - I think I got turned around on the relates and primary resource - I will sort that out now
3 - data request - yup - agreed
4 - related project - but different data and methods - could be linked for sure .

I will update when these are done. Thanks again!

**Comment by timvdstap** [comment]
I think it looks great @hakaiholmes are you OK for me to publish?

**Comment by hakaiholmes** [comment]
Great thank you!
