### ISSUE TITLE
Dataset - Real-Time Provisional High-Resolution Record of Seawater Carbon Dioxide Content Collected from the Nova Harvest Ltd Hatchery in Bamfield BC Canada

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#66]
## Real-Time Provisional High-Resolution Record of Seawater Carbon Dioxide Content Collected from the Nova Harvest Ltd Hatchery in Bamfield BC Canada

https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/tV5qE0aUgaOjSVmgPgiZ6MyHuSy1/-NdH-jgHZQzKrYdb2nw_

### In General

- [x] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [x] No version information in the title
- [ ] Frontloaded (with the most important information first)
- [x] Include the geographical region the data apply to
- [ ] Short – aim for 60 characters including spaces
- [x] Does not include acronyms – put these in the keywords
- [x] Does not include the word “dataset”
- [x] Time series datasets should include “time series” at the end of the title

#### Abstract

- [x] Abbreviations have been expanded upon at first mention
- [ ] Abstract describes how, when, what, where, why of data collection and is limited to no more than 500 words

#### DOI

- [ ] A DOI has been drafted for this record
- [ ] DOI has been updated via the form after review and changes to record
- [ ] DOI has been manually edited on datacite fabrica
- [ ] DOI status has been changed from Draft to Findable

### Spatial

- [x] Ensure that Depth or Height Positive is correctly selected

### Contact

- [x] ROR and ORCID(s) are included and linked properly where applicable
- [x] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [x] Include Hakai Institute as Publisher and include data@hakai.org as email
- [x] Make sure email address is provided if the role is 'Metadata Custodian' or 'Point of Contact' 
- [x] Add contact affiliation where known including ROR
- [x] Use institutional email adresses where possible for contacts

### Resources

- [x] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [ ] Readme, changelog, data dictionary, protocols included in data-package
- [ ] An archive folder for older data versions is included in the data package if the version is _not_ 1.0
- [ ] Links work
- [ ] All files in the data package can be opened and are not corrupt
- [ ] No executable files in the data package. Files should be open formats and standards (.csv, .txt for example)

**Comment by JessyBarrette** [comment]
@Br-Johnson this is a new dataset that would need to be made available asap online. 

I essentially copied metadata from another similar dataset and updated the related fields. @KT-Pocock did review the dataset.

This is related to https://github.com/HakaiInstitute/hakai-datasets/issues/155

**Comment by JessyBarrette** [comment]
It is strange that the link above to the metadata record isn't working. This is the related record. 

https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/tV5qE0aUgaOjSVmgPgiZ6MyHuSy1/-NdH-jgHZQzKrYdb2nw_

This issue was generated right after I submitted the dataset record. Something is going on with the script to generate those issues maybe.

**Comment by Br-Johnson** [comment]
@JessyBarrette Couple of notes based on reviewing the check list:

Title:
- I might suggest changing the title so that Sea Water Carbon Content comes first.
- Might also want to shorten title. suggest putting 'High resolution' in the abstract, and re-wording to remove the word 'record'

Abstract:
- Perhaps include temporal range. when did these measurements start?
- Add why these measurements are important or what they could / will be used for

Spatial
- Abstract says sea surface measurements but depth is 20 m? Clarify depth in abstract?

Other:
- ORCIDs and RORs are missing
- The link to the dataset doesn't work 
- Would suggest taking the word ERDDAP out of the name of the resource and give it a more descriptive name, like a shortened version of the metadata record title.  
- Is there a version associated with this dataset?
- Do you want a DOI for this dataset? I'm guessing not since it's not a snapshot of data, and it's also not research grade

Notes: You have to list Hakai Insitute soley as publisher and then include in citation for it to appear correctly. So, I made Wiley the Data Owner instead of Hakai. Which is fine since Wiley has the legal authority to act as owner on behalf of Hakai and is the PI....

**Comment by JessyBarrette** [comment]
Thanks Brett, 
I replaced the points in your comment by some checkbox to help track.

### title
This title follow similar datasets that are already present within our ERDDAP for similar sites at different stations (see all BoL realtime datasets [here](https://catalogue.hakai.org/erddap/tabledap/allDatasets.htmlTable?datasetID%2Cinstitution%2Ctitle%2Ctabledap%2Cmetadata&datasetID=~%22.*BoL.*%22)). For consistency and historical reasons, it may be better to keep the title pattern. I realized that I removed the `(CO2)` in the title but should maybe add it back for the same reason.

Abstract: 
- temporal range: there's already an input in the form for that. I'm not sure if it's mandatory to add something in the abstract too.
- why?: I won't comment and leave it for the OA group.

Spatial:
- a reference to the 20m depth intake was added to the abstract

Other
- ORCID: added
- the link to the dataset? The ERDDAP dataset isn't yet online and we're waiting on the record release to make it available.
- ERDDAP ressource name. Traditionally this has been the name used to define a link to the related ERDDAP dataset.
- This is version 1 which is the default value too
-  No DOI for this realtime dataset, at least for now. Typically, a DOI is generated for the research dataset which is a revised version which is uploaded to NCEI. 
-

**Comment by Br-Johnson** [comment]
Cool. Looks good to me. I will leave it to you to publish the record when you have the data up on ERDDAP.
