### ISSUE TITLE
Dataset - Elliot Creek Landslide - 2023 - Hakai Airborne Coastal Observatory

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#83]
## Elliot Creek Landslide - 2023 - Hakai Airborne Coastal Observatory

<https://hakaiinstitute.github.io/hakai-metadata-entry-form/#/en/hakai/RvRPlFMSsIaBwoGdQIq5BVYfBBa2/-NpRZqJivYfce75NOoBD>

### In General

- [ ] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [x] No version information in the title
- [x] Frontloaded (with the most important information first)
- [x] Include the geographical region the data apply to
- [x] Short – aim for 60 characters including spaces
- [x] Does not include acronyms – put these in the keywords
- [x] Does not include the word “dataset”
- [ ] Time series datasets should include “time series” at the end of the title

#### Abstract

- [ ] Abbreviations have been expanded upon at first mention
- [ ] Abstract describes how, when, what, where, why of data collection and is limited to no more than 500 words

#### DOI

- [x] A DOI has been drafted for this record
- [ ] DOI has been updated via the form after review and changes to record
- [ ] DOI has been manually edited on datacite fabrica
- [ ] DOI status has been changed from Draft to Findable

### Spatial

- [x] Ensure that Depth or Height Positive is correctly selected

### Contact

- [x] ROR and ORCID(s) are included and linked properly where applicable
- [x] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [x] Include Hakai Institute as Publisher and include data@hakai.org as email
- [x] Make sure email address is provided if the role is 'Metadata Custodian' or 'Point of Contact' 
- [x] Add contact affiliation where known including ROR
- [x] If resource is (partially) generated by Hakai researchers, include 'Tula Foundation' (with associated ROR) with 'Funder' role. Be sure to uncheck 'include in citation' for Tula Foundation.

### Resources

- [ ] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [ ] Readme, changelog, data dictionary, protocols included in data-package (for tabular text based data)
- [ ] An archive folder, or other means, for older data versions is included in the data package if the version is _not_ 1.0
- [x] Links work
- [x] All files in the data package can be opened and are not corrupt
- [x] No executable files in the data package. Files should be open formats and standards (.csv, .txt for example)

**Comment by timvdstap** [comment]
Hey @hakaiholmes - again sorry, working my way through a list of submitted records as we speak!

## General
- Is this record a continuation of the work described in this record: https://doi.org/10.21966/r30c-a485 ? If so, would you consider the webmap to be an entirely new product or a new version of the 2022 webmap (and therefore, perhaps better to update existing record). My guess is that this would be a new product?

## Resource Identification
- I would perhaps recommend expanding the abbreviations of LiDAR and GLOF
- I would remove the Hakai Institute as keyword, but perhaps add ACO/Airborne Coastal Observatory

## Contact
- 'Hakai Institute' is currently listed as the main author, but I also see 'Hakai Geospatial' in the contacts. Should the main author (and associated roles) be 'Hakai Geospatial' instead?
- I have removed 'Geospatial Science' and the individual email from the 'Hakai Institute' contact
- Hakai Geospatial currently has the role 'Publisher', but the Publisher would be Hakai Institute. 
- Good to review the contact and how you'd like Hakai Geospatial to be represented: see #111

## Data and Documentation
- Is it possible that the link to the webmap is specific to the area surveyed that is described in this metadata record?
- I would include the metadata report link under 'Related Works' with the relation type being 'Has Metadata' as the related work will have the metadata for the primary resource.
- Just confirming that there's no specific DMP for this project that you could include under Related Works, correct?
- If this is indeed a new version of the 2022 Elliot Creek Landslide record then you can include that DOI (https://doi.org/10.21966/r30c-a485) as a related work as well (I would do relation type = 'Continues', rather than 'Is New Version Of')

**Comment by timvdstap** [comment]
Hey @hakaiholmes I see this record is published but this GitHub issue is still outstanding, and the DOI is still in draft. Could you perhaps have another quick review of the metadata and my suggestions above? If all looks good please let me know, then I can make the DOI Findable and close this issue.

**Comment by hakaiholmes** [comment]
Edits completed to the record. 
Should be good to go, but ping me if you see any other issues.

**Comment by timvdstap** [comment]
Thanks @hakaiholmes looks good to me! Few minor things I changed: 

- Added Hakai Institute as Publisher, now included in the citation
- Rather than linking to the URL for the 2022 metadata report, I linked to DOI for that record

I'll update the record in DataCite and close this issue -- feel free to reopen if you have any questions or concerns, or if you disagree with those changes!
