### ISSUE TITLE
Dataset - Cryosphere Snow Surveys - 2023 - Hakai Airborne Coastal Observatory

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#85]
## Cryosphere Snow Surveys - 2023 - Hakai Airborne Coastal Observatory

<https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/RvRPlFMSsIaBwoGdQIq5BVYfBBa2/-NpRfMcU9I8mMcBH6qiv>

### In General

- [ ] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [x] No version information in the title
- [x] Frontloaded (with the most important information first)
- [ ] Include the geographical region the data apply to
- [ ] Short – aim for 60 characters including spaces
- [ ] Does not include acronyms – put these in the keywords
- [x] Does not include the word “dataset”
- [ ] Time series datasets should include “time series” at the end of the title

#### Abstract

- [ ] Abbreviations have been expanded upon at first mention
- [ ] Abstract describes how, when, what, where, why of data collection and is limited to no more than 500 words

#### DOI

- [x] A DOI has been drafted for this record
- [ ] DOI has been updated via the form after review and changes to record
- [ ] DOI has been manually edited on datacite fabrica
- [ ] DOI status has been changed from Draft to Findable

### Spatial

- [x] Ensure that Depth or Height Positive is correctly selected

### Contact

- [x] ROR and ORCID(s) are included and linked properly where applicable
- [x] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [x] Include Hakai Institute as Publisher and include data@hakai.org as email
- [x] Make sure email address is provided if the role is 'Metadata Custodian' or 'Point of Contact' 
- [x] Add contact affiliation where known including ROR
- [x] If resource is (partially) generated by Hakai researchers, include 'Tula Foundation' (with associated ROR) with 'Funder' role. Be sure to uncheck 'include in citation' for Tula Foundation.

### Resources

- [ ] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [ ] Readme, changelog, data dictionary, protocols included in data-package (for tabular text based data)
- [ ] An archive folder, or other means, for older data versions is included in the data package if the version is _not_ 1.0
- [x] Links work
- [x] All files in the data package can be opened and are not corrupt
- [ ] No executable files in the data package. Files should be open formats and standards (.csv, .txt for example)

**Comment by timvdstap** [comment]
Hey @hakaiholmes I noticed that this ticket is still outstanding even though the record has been published. I figured I'd give it a quick review still, so that I can close this issue -- hope that's OK with you! Some thoughts:

- Wondering what your thoughts are regarding adding geographic extent in the title but removing 'Hakai Airborne Coastal Observatory'?
- Is this record a continuation of existing Cryosphere records (https://catalogue.hakai.org/dataset/?q=Cryosphere&ext_bbox=&ext_layers=) that are published in the catalogue?
- I would expando n SWE and RPAS in the abstract
- I think you can remove 'Hakai Institute' as keyword
- Contact section looks great!
- Both the Primary Resource and Related Work links to the 2023 cryosphere metadata report. Should perhaps the primary resource link to the webmap (if publicly available) or the Data Request Form, with the metadata report included as Related Work (relation type: "Has Metadata")?

**Comment by hakaiholmes** [comment]
Thanks for this - I will make these edits tomorrow and will keep you posted.

**Comment by hakaiholmes** [comment]
Edited based on the comments above - have a look to confirm I have those related documents linked up and categorized properly. 
https://hakaiinstitute.github.io/hakai-metadata-entry-form/#/en/hakai/RvRPlFMSsIaBwoGdQIq5BVYfBBa2/-NpRfMcU9I8mMcBH6qiv

**Comment by timvdstap** [comment]
That looks right to me @hakaiholmes - while I had linked to the cryosphere records in our catalogue, it hadn't actually clicked before for me that there's already 4 years of cryosphere geospatial data in our catalogue, which is pretty awesome! I'm wondering if there's a specific reason for having a unique metadata record for each year? Perhaps in the new year we can chat about whether it makes more sense to have a single cryosphere time series record in the catalogue, which you can update annually rather than creating a new one.

I've updated the information in DataCite. 

I'll close this ticket for now - as always, feel free to reopen if you want!
